sudo: required

language: ruby

services:
  - docker

before_script:
  - docker-compose build
  - docker-compose up -d db
  - sleep 30

script:
  - docker-compose up flyway
  - docker-compose up flyway-alpine

after_script:
  - docker-compose down
