sudo: required

language: ruby

services:
  - docker

env:
  - COMPOSE_FILE=docker-compose.mysql5.yml
  - COMPOSE_FILE=docker-compose.mysql8.yml

before_script:
  - docker-compose up -d db
  - sleep 30

script:
  - docker-compose build
  - docker-compose up flyway
  - docker-compose up flyway-alpine

after_script:
  - docker-compose down
