sudo: required

language: ruby

services:
  - docker

env:
  - COMPOSE_FILE=mysql5/docker-compose.yml
  - COMPOSE_FILE=mysql8/docker-compose.yml

before_script:
  - docker-compose up -d db
  - sleep 30

script:
  - docker-compose build
  - docker-compose up flyway
  - docker-compose up flyway-alpine

after_script:
  - docker-compose down
