version: "3"
services:
  flyway:
    build:
      context: ..
    command: -url=jdbc:mysql://db -schemas=myschema -user=root -password=P@ssw0rd migrate
    volumes:
      - ../test/sql:/flyway/sql
    depends_on:
    - db
  flyway-alpine:
    build:
      context: alpine
    command: -url=jdbc:mysql://db -schemas=myschema -user=root -password=P@ssw0rd migrate
    volumes:
      - ../test/sql:/flyway/sql
    depends_on:
    - db
  db:
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=P@ssw0rd
